export const FETCH_REVIEWDATA_REQUEST = 'FETCH_REVIEWDATA_REQUEST';
export const FETCH_REVIEWDATA_SUCCESS = 'FETCH_REVIEWDATA_SUCCESS';
export const FETCH_REVIEWDATA_FAIL = 'FETCH_REVIEWDATA_FAIL';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';




